version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: jokes_postgres_container
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jokes_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./databases/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: